### ISSUE TITLE
Wrong chat calculation

### ISSUE THREAD

**Issue by Arbuzio** [gryffon/ringteki#1692] opened 2018-03-10 18:29 UTC
I used box = in game all ok (2-1), chat still says 2-4
![image](https://user-images.githubusercontent.com/32962101/37245507-5201e56a-2499-11e8-8e9c-42ce6e3b4fab.png)

**Comment by jeremylarner** [comment] 2018-03-10 22:33
Yeah, that's a known issue (duplicate of #1500). Fixed by #1683

**Closed** 2018-03-13 04:42 UTC
Labels: duplicate
