### ISSUE TITLE
Reprieve and Way of the crab interacting incorrectly

### ISSUE THREAD

**Issue by VoidPirateSam** [gryffon/ringteki#1685] opened 2018-03-08 20:25 UTC
When Way of the crab is played and the sacrificed character is saved by reprieve the effect continues even though the event should stay in hand unplayed since the sacrifice is part of the cost.

**Comment by jeremylarner** [comment] 2018-03-08 22:01
Thanks for the report - this is a known issue (duplicate of #1519)

**Closed** 2018-03-10 08:06 UTC
Labels: duplicate
