### ISSUE TITLE
Ring Effects on Mouseover

### ISSUE THREAD

**Issue by Void2258** [gryffon/ringteki#914] opened 2017-11-09 14:04 UTC
Ring effects aren't listed anywhere, requiring that you open a separate window to the wiki or have the reference card next to you at all times so you remember what they do. Please show the ring effect on mouseover.

**Comment by jamesoddy** [comment] 2019-07-24 15:05
Duplicate of #3355.
Closing this issue due to age.

**Closed by jamesoddy** 2019-07-24 15:05 UTC
Labels: UI/client, enhancement
