### ISSUE TITLE
Unable to select which ring to resolve

### ISSUE THREAD

**Issue by CDMayberry** [gryffon/ringteki#2909] opened 2019-02-15 16:39 UTC
Possible UI bug when selecting one of two rings to activate, or DoP... Attacking PHX vs defending Dragon, PHX has Seeker in play, Dragon uses DoP, but apparently wasn't given the option to properly select either of the rings.

![powerbug2](https://user-images.githubusercontent.com/2746687/52870526-1271cc00-3116-11e9-86e0-b6d3943b8bb7.PNG)
![powerbug3](https://user-images.githubusercontent.com/2746687/52870538-17cf1680-3116-11e9-8b36-ebadfee560eb.PNG)

**Comment by CDMayberry** [comment] 2019-02-15 16:42
Additional Note: Game apparently came to a halt and the users were kicked out after he was forced to select the air ring.

**Comment by Syrail** [comment] 2019-02-15 20:26
Just tested this interaction - The issue is that the contested ring has moved to the claimed pool of the person using Display of Power. The ring can be clicked there to resolve its primary element. 

This will be problematic if there are multiple claimed rings when someone uses Display of Power, (The rings for different elements could be in up to 3 different locations) so we may wish to move it to using a standard prompt to choose which rings to resolve.

**Comment by jamesoddy** [comment] 2019-05-13 15:58
An alternative ring select prompt is being looked into.  I will close this issue as it is not a bug (more like a design fault).

**Closed by jamesoddy** 2019-05-13 15:58 UTC
Labels: bug
