### ISSUE TITLE
Iron mine and sacrifice

### ISSUE THREAD

**Issue by shinjosky** [gryffon/ringteki#1726] opened 2018-03-18 11:40 UTC
Hello, i know this kind of issue has been somewhat reported but today my opponent prevented the sacrifice of the vanguard warrior and used his ability none the less.
If i read correctly the Rules reference appendix III questions and answers and the note in https://fiveringsdb.com/card/iron-mine, he couldn't, am I right?

**Comment by jeremylarner** [comment] 2018-03-18 20:07
Yes, that's a bug.  It is legal to prevent the sacrifice, but if you do so, then the ability should fizzle, which it doesn't do currently on jigoku.  I have a fix which will hopefully make it to the live server soon, but last time I tried to fix this issue it crashed the whole server, so we're deploying it very carefully...

Duplicate of #1519

**Closed** 2018-03-19 23:44 UTC
Labels: duplicate
