### ISSUE TITLE
Way of the Crab resolves normally even when cost is prevented.

### ISSUE THREAD

**Issue by Fite-Ian** [gryffon/ringteki#1603] opened 2018-02-01 03:15 UTC
In a match today, my opponent used Way of the Crab then used Iron Mine's interrupt to prevent his character from leaving play.  This should cause WotC to return to his hand without resolving as the cost has not been paid but instead it resolved normally causing me to sacrifice a character.  I have not tested this with other cards such as Noble Sacrifice or other ways of preventing the sacrifice such as Reprieve.

**Comment by jeremylarner** [comment] 2018-02-01 04:50
Thanks for the report - this is a known issue.  Duplicate of #1519

**Closed** 2018-02-02 09:30 UTC
Labels: duplicate
