### ISSUE TITLE
Card Size and Use of Screen (request)

### ISSUE THREAD

**Issue by tobinlopes** [gryffon/ringteki#474] opened 2017-10-15 03:48 UTC
Hey folks,

The aspect between card size and screen use seems out of whack. I'm wondering if more of the screen can be used. Right now it seems that about 1/2 the screen is the playing surface. Might there be a way to increase this to 60%? Just a bit more would be a big difference.
-tpl

**Comment by jeremylarner** [comment] 2017-10-15 06:56
I'm not exactly sure what the problem is.  Is it just that the cards are too small?  If so, there's an option in your profile to make them bigger.

**Comment by tobinlopes** [comment] 2017-10-15 14:10
During the games I switched the cards sizes a bit, and I'm playing on a laptop so my screen isn't the largest - and there was a lot of overlap with the "Large" size and I felt it hard to see with Standard. When I was using standard there was a lot of unused space on the right - but when I went large the space disappeared but the overlap was introduced. So, yeah, it's not easy to identify what can be changed to improve it - if anything.

However, in taking a closer look at both screens and thinking about it, the Province Deck is wasted space once the game begins - just a card image. Maybe instead of a full image you could make it 25% size and then move the Role and SH cards over to the player's left a bit more?

![image](https://user-images.githubusercontent.com/3495881/31585513-311e6eae-b180-11e7-93f1-394addcde2d6.png)

But upon further reflection, not so easy to figure out things. Maybe the Honor, Fate, and hand size can be moved to the screen similar to jinteki? Maybe that goes over the province card or in another movable box and that space is gained from the top and bottom. 

In either case it seems tougher than I first thought. :)

-tpl

**Comment by YogoGohei** [comment] 2017-10-19 13:39
Throwing in my two cents:

Is there any particular reason the province deck is handled this way?  

Wouldn't it be clearer (and more in tune with how the physical game is played) to just show us the 5 provinces as soon as the game starts, have us pick one, and then move on?  I am not sure why there is a deck shown on screen at any point, let alone for the entire duration of the game after the first few moments.  

You could then utilize that space for... something.  Role, maybe?  It seems like putting the stronghold there (which you actually bow and interact with) is asking for trouble.  But you never really touch your role, so having it in a spot where it is shown and never touched would free up an, admittedly, minor amount of room.

**Comment by dodgepong** [comment] 2017-10-19 13:53
Generally speaking I feel like both the honor dial and empty province deck take up way too much screen real estate. I would guess that Player Name, Honor, Fate, Honor Bid, and probably first player could all fit into that section.

**Comment by YogoGohei** [comment] 2017-10-19 13:58
If nothing else, removing those from the screen would give the rings more room to spread out on smaller monitors.

**Comment by jeremylarner** [comment] 2017-10-19 15:03
I can see what you're saying, but the space issue mostly stems from the fact that you have to have 6 cardlengths of space on your screen top to bottom.  I hear very few complaints of insufficient screen width (rather, I get lots of people telling me that there's a lot of wasted space on the right of their screen), but the space problems people have with cards ending up underneath or on top of other cards are caused by the fact that the cards are too big for them to be able to fit 6 rows of cards.

Having said that, there is talk of developing a skill counter-type asset, and maybe we'll put it where the province decks are at the moment.

**Comment by gryffon** [comment] 2017-10-26 03:44
I think that after we get a stable 1.0 release, a UI pass will be a priority. We will come back to this at that point, and try to figure out some good options.

**Comment by GymKirk** [comment] 2018-06-25 14:41
Can you give the option to make the zoomed in card bigger? I still find it hard to read. On jinteki (Netrunner), the card is larger

**Comment by jamesoddy** [comment] 2019-07-24 15:10
UI overhauled now due to #2441 
Closing this ticket as no longer relevant.

**Closed by jamesoddy** 2019-07-24 15:10 UTC
Labels: enhancement
